name = "cloudbase-crm"
main = "src/index.ts"
compatibility_date = "2024-03-21"

[[d1_databases]]
binding = "DB"
database_name = "cloudbase-db"
database_id = "e3f00142-276f-46a9-bf9f-ee3b94827cb9"


[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cloudbase-assets"

[ai]
binding = "AI"

[vars]
JWT_SECRET = "dev-secret-123"

# Add this at the bottom
[triggers]
crons = ["0 13 * * *"] # Runs at 13:00 UTC (8:00 AM Creston time)