name = "chalkboard-dashboard"
compatibility_date = "2024-03-21"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "chalkboard-db"
database_id = "faf9a32b-1947-4cbb-a41f-6fe96d245fcc"

[[r2_buckets]]
binding = "CHALKBOARD_ASSETS"
bucket_name = "chalkboard-assets"

[vars]
JWT_SECRET = "chalkboard-dev-secret"
